name: Test Sandbox
on: push
jobs:
  sandbox:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [14, 16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: (yarn && yarn test:sandbox:ci) || NEAR_WORKSPACES_DEBUG=true yarn test:sandbox:ci --verbose --noStackTrace