name: Test Testnet
on: push
jobs:
  testnet:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test:testnet:ci --fail-fast
