name: Test Sandbox
on: push
jobs:
  sandbox:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn
      - name: Run tests
        run: yarn test:sandbox:ci --fail-fast
