name: Test Testnet
on: push
jobs:
  testnet:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ matrix.platform }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v2
        with:
          path: '/home/workspaces/.near-credentials/near-workspaces'
          key: ${{ matrix.platform }}-${{ hashFiles('$HOME/.near-credentials/near-workspaces/testnet/*') }}
      - name: yarn
        run: yarn
      - name: Run tests
        run: yarn test:testnet:ci --fail-fast
  testnet-nocache:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn
      - name: Run tests
        run: yarn test:testnet:ci --fail-fast
  testnet-clean-accs:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn
      - name: Run tests
        run: yarn test:testnet:ci --fail-fast
      - name: Clean accounts
        run: yarn clean:accounts